/**
 * Copyright Tyto Software Pvt. Ltd.
 */
__sahiDebug__("user_ext.js: start");

// Uncomment the line below if pages with WebSockets do not work properly. 
// window.WebSocket = null;

SflWrapper.prototype.addCustomMetaData = function(){
	/*
	this.addMetaData({qn: "spark.components::Button", attributes: ["encaps_spark.components::ComboBox", "label", "text", "name", "automationName", "toolTip", "id", "autoGeneratedName", "index"], action: "click", value: "label"});

	 */
}
__sahiDebug__("user_ext.js: end");
