/* version 4.3.2 start */
CREATE TABLE IF NOT EXISTS SUITEREPORTS (ID BIGINT NOT NULL AUTO_INCREMENT, SUITEREPORTID VARCHAR(255), SUITENAME VARCHAR(2000), SUITEPATH VARCHAR(2000), STARTTIME TIMESTAMP, ENDTIME TIMESTAMP, STATUS VARCHAR(255), TOTALCOUNT INT, PASSEDCOUNT INT, FAILEDCOUNT INT, TIMETAKEN INT, BROWSERTYPE VARCHAR(255), PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS NODEREPORTS(ID BIGINT NOT NULL AUTO_INCREMENT, SUITEREPORTID VARCHAR(255), HOST VARCHAR(255), PORT VARCHAR(255), SCRIPTCOUNT INT, PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS SCRIPTREPORTS(ID BIGINT NOT NULL AUTO_INCREMENT, SCRIPTREPORTID VARCHAR(255), SCRIPTNAME VARCHAR(2000), SUITENAME VARCHAR(2000), SUITEREPORTID VARCHAR(255), TOTALSTEPS INT, FAILURES INT, ERRORS INT, TIMETAKEN INT, NODEHOST VARCHAR(255), NODEPORT VARCHAR(255), STATUS VARCHAR(255), `LOAD` INT, PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS STEPREPORTS(ID BIGINT NOT NULL AUTO_INCREMENT, MESSAGE VARCHAR(2000), DEBUGINFO VARCHAR(2000), MESSAGETYPE VARCHAR(255), SCRIPTREPORTID VARCHAR(255), FAILUREMESSAGE VARCHAR(4000), MESSAGETIMESTAMP TIMESTAMP, PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS TESTCASEREPORTS(ID BIGINT NOT NULL AUTO_INCREMENT, TESTCASEREPORTID VARCHAR(255), SCRIPTREPORTID VARCHAR(255), SUITEREPORTID VARCHAR(255), DESCRIPTION VARCHAR(4000), STATUS VARCHAR(255), TIMETAKEN INT, SCRIPTNAME VARCHAR(2000), PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS CSVREPORTS(ID BIGINT NOT NULL AUTO_INCREMENT, SUITEREPORTID VARCHAR(255), CSV VARCHAR(10000), PRIMARY KEY(ID));
CREATE TABLE SAHIINFO(`KEY` VARCHAR(255), VALUE VARCHAR(255));
CREATE INDEX SUITEREPORTS_SUITE_REPORT_ID ON SUITEREPORTS (SUITEREPORTID);
CREATE INDEX NODEPORTS_SUITE_REPORT_ID ON NODEREPORTS (SUITEREPORTID);
CREATE INDEX SCRIPTREPORTS_SUITE_REPORT_ID ON SCRIPTREPORTS (SUITEREPORTID);
CREATE INDEX SCRIPTREPORTS_SCRIPT_REPORT_ID ON SCRIPTREPORTS (SCRIPTREPORTID);
CREATE INDEX STEPREPORTS_SCRIPT_REPORT_ID ON STEPREPORTS (SCRIPTREPORTID);
CREATE INDEX TESTCASEREPORTS_SUITE_REPORT_ID ON TESTCASEREPORTS (SUITEREPORTID);
CREATE INDEX TESTCASEREPORTS_SCRIPT_REPORT_ID ON TESTCASEREPORTS (SCRIPTREPORTID);
CREATE INDEX TESTCASEREPORTS_TESTCASE_REPORT_ID ON TESTCASEREPORTS (TESTCASEREPORTID);
CREATE INDEX CSVREPORTS_SUITE_REPORT_ID ON CSVREPORTS (SUITEREPORTID);

ALTER TABLE STEPREPORTS ADD SCREENSHOT VARCHAR(255);
ALTER TABLE SUITEREPORTS ADD SUITEINFO VARCHAR(4000);
ALTER TABLE SUITEREPORTS ADD USERDEFINEDID VARCHAR(255);
ALTER TABLE STEPREPORTS MODIFY `DEBUGINFO` VARCHAR(4000);
ALTER TABLE STEPREPORTS MODIFY `MESSAGE` VARCHAR(4000); 

/* version 4.3.2 end */
/* version 4.5 start  */

ALTER TABLE CSVREPORTS CHANGE CSV CSV TEXT;
ALTER TABLE SCRIPTREPORTS ADD TCCOUNT INT, ADD TCPASSED INT, ADD TCFAILED INT;
ALTER TABLE SUITEREPORTS ADD TCCOUNT INT, ADD TCPASSED INT, ADD TCFAILED INT;

/* version 4.5 end  */
/* version 4.5.2 start */

ALTER TABLE STEPREPORTS ADD STEPID INT;

/* version 4.5.2 end */
/* version 4.6 start */


CREATE TABLE IF NOT EXISTS HARPAGES(ID VARCHAR(767), PAGEDATA TEXT, REQUESTSTARTTIME VARCHAR(100), PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS HARREQUESTRESPONSE(ID VARCHAR(767), REQUESTRESPONSEDATA TEXT, SENDTIME BIGINT, WAITTIME BIGINT, RECEIVETIME BIGINT, PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS QUERYLOG (ID BIGINT NOT NULL AUTO_INCREMENT, LAUNCHERID VARCHAR(255), QUERY TEXT, PRIMARY KEY(ID));
CREATE INDEX QUERYLOG_ID on QUERYLOG (ID);   
CREATE INDEX HARPAGES_ID on HARPAGES (ID);
CREATE INDEX HAR_REQUEST_RESPONSE_ID on HARPAGES (ID);
ALTER TABLE SCRIPTREPORTS ADD SCRIPTRELPATH VARCHAR(1000);
ALTER TABLE SCRIPTREPORTS ADD STARTURL VARCHAR(4000);
ALTER TABLE SCRIPTREPORTS ADD LAUNCHERID VARCHAR(255);

/* version 4.6 end */

/* version 5.0.6 start */

ALTER TABLE SUITEREPORTS CHANGE ENDTIME ENDTIME DATETIME;
ALTER TABLE SUITEREPORTS CHANGE STARTTIME STARTTIME DATETIME;
ALTER TABLE STEPREPORTS CHANGE MESSAGETIMESTAMP MESSAGETIMESTAMP DATETIME;

/* version 5.0.6 end */

/* version 5.0.8 start */

CREATE INDEX QUERYLOG_LAUNCHERID on QUERYLOG (LAUNCHERID);

/* version 5.0.8 end */

ALTER TABLE SCRIPTREPORTS ADD SCRIPTARGS VARCHAR(5000);

/* version 5.2 start */

ALTER TABLE HARREQUESTRESPONSE ADD SCRIPTREPORTID VARCHAR(512);
ALTER TABLE HARREQUESTRESPONSE ADD SUITEREPORTID VARCHAR(512);
ALTER TABLE HARREQUESTRESPONSE ADD URL VARCHAR(4092);
ALTER TABLE HARREQUESTRESPONSE ADD STEPID VARCHAR(255);
ALTER TABLE HARREQUESTRESPONSE ADD LOADCOUNT VARCHAR(255);

ALTER TABLE STEPREPORTS MODIFY `SCREENSHOT` VARCHAR(4000) ;
/* version 5.2 end */