CREATE TABLE IF NOT EXISTS suiteReports (id BIGINT IDENTITY, suiteReportId VARCHAR(255), suiteName VARCHAR(2000), suitePath VARCHAR(2000), startTime TIMESTAMP, endTime TIMESTAMP, status VARCHAR(255), totalCount INT, passedCount INT, failedCount INT, timeTaken INT, browserType VARCHAR(255));
CREATE TABLE IF NOT EXISTS nodeReports (id BIGINT IDENTITY, suiteReportId VARCHAR(255), host VARCHAR(255), port VARCHAR(255), scriptCount INT);
CREATE TABLE IF NOT EXISTS scriptReports (id BIGINT IDENTITY, scriptReportId VARCHAR(255), scriptName VARCHAR(2000), suiteName VARCHAR(2000), suiteReportId VARCHAR(255), totalSteps INT, failures INT, errors INT, timeTaken INT, nodeHost VARCHAR(255), nodePort VARCHAR(255), status VARCHAR(255), `load` INT);
CREATE TABLE IF NOT EXISTS stepReports (id BIGINT IDENTITY, message VARCHAR(2000), debugInfo VARCHAR(2000), messageType VARCHAR(255), scriptReportId VARCHAR(255), failureMessage VARCHAR(4000), messageTimestamp TIMESTAMP);
CREATE TABLE IF NOT EXISTS testCaseReports(id BIGINT IDENTITY, testCaseReportId VARCHAR(255), scriptReportId VARCHAR(255), suiteReportId VARCHAR(255), description VARCHAR(4000), status VARCHAR(255), timeTaken INT, scriptName VARCHAR(2000));
CREATE TABLE IF NOT EXISTS csvReports(id BIGINT IDENTITY, suiteReportId VARCHAR(255), csv VARCHAR(100000));
CREATE TABLE IF NOT EXISTS sahiInfo(key VARCHAR(255), value VARCHAR(255));
CREATE INDEX IF NOT EXISTS SUITEREPORTS_SUITE_REPORT_ID on suiteReports (suiteReportId);
CREATE INDEX IF NOT EXISTS NODEPORTS_SUITE_REPORT_ID on nodeReports (suiteReportId);
CREATE INDEX IF NOT EXISTS SCRIPTREPORTS_SUITE_REPORT_ID on scriptReports (suiteReportId);
CREATE INDEX IF NOT EXISTS SCRIPTREPORTS_SCRIPT_REPORT_ID on scriptReports (scriptReportId);
CREATE INDEX IF NOT EXISTS STEPREPORTS_SCRIPT_REPORT_ID on stepReports (scriptReportId);
CREATE INDEX IF NOT EXISTS TESTCASEREPORTS_SUITE_REPORT_ID on testCaseReports (suiteReportId);
CREATE INDEX IF NOT EXISTS TESTCASEREPORTS_SCRIPT_REPORT_ID on testCaseReports (scriptReportId);
CREATE INDEX IF NOT EXISTS TESTCASEREPORTS_TESTCASE_REPORT_ID on testCaseReports (testCaseReportId);
CREATE INDEX IF NOT EXISTS CSVREPORTS_SUITE_REPORT_ID on csvReports (suiteReportId);

CREATE TABLE IF NOT EXISTS harPages(id VARCHAR(1000), pageData VARCHAR(100000), requestStartTime VARCHAR(100));
CREATE INDEX IF NOT EXISTS HARPAGES_ID on harPages (id);
CREATE TABLE IF NOT EXISTS harRequestResponse(id VARCHAR(1000), requestResponseData VARCHAR(100000), sendTime BIGINT, waitTime BIGINT, receiveTime BIGINT);
CREATE INDEX IF NOT EXISTS HAR_REQUEST_RESPONSE_ID on harPages (id);

ALTER TABLE scriptReports ADD IF NOT EXISTS suiteName VARCHAR(2000);
ALTER TABLE stepReports ADD IF NOT EXISTS screenShot VARCHAR(255);
ALTER TABLE scriptReports ADD IF NOT EXISTS suiteName VARCHAR(2000);
ALTER TABLE scriptReports ADD IF NOT EXISTS `load` int;
ALTER TABLE stepReports ALTER COLUMN `failureMessage` VARCHAR(4000);
ALTER TABLE suiteReports ADD IF NOT EXISTS suiteInfo VARCHAR(4000);
ALTER TABLE suiteReports ADD IF NOT EXISTS userDefinedId VARCHAR(255);

ALTER TABLE stepReports ALTER COLUMN `debugInfo` VARCHAR(4000) ;
ALTER TABLE stepReports ALTER COLUMN `message` VARCHAR(4000);

ALTER TABLE SCRIPTREPORTS ADD IF NOT EXISTS TCCOUNT INT;
ALTER TABLE SCRIPTREPORTS ADD IF NOT EXISTS TCPASSED INT;
ALTER TABLE SCRIPTREPORTS ADD IF NOT EXISTS TCFAILED INT;
ALTER TABLE SUITEREPORTS ADD IF NOT EXISTS TCCOUNT INT;
ALTER TABLE SUITEREPORTS ADD IF NOT EXISTS TCPASSED INT;
ALTER TABLE SUITEREPORTS ADD IF NOT EXISTS TCFAILED INT;

ALTER TABLE STEPREPORTS ADD IF NOT EXISTS STEPID INT;
CREATE TABLE IF NOT EXISTS queryLog (id BIGINT IDENTITY, launcherId VARCHAR(255), query VARCHAR(100000));   
CREATE INDEX IF NOT EXISTS QUERYLOG_ID on queryLog (id);
ALTER TABLE SCRIPTREPORTS ADD IF NOT EXISTS scriptRelPath VARCHAR(1000);
ALTER TABLE SCRIPTREPORTS ADD IF NOT EXISTS startUrl VARCHAR(4000);
ALTER TABLE SCRIPTREPORTS ADD IF NOT EXISTS launcherId VARCHAR(255);
ALTER TABLE SCRIPTREPORTS ADD IF NOT EXISTS scriptArgs VARCHAR(5000);

CREATE INDEX IF NOT EXISTS QUERYLOG_LAUNCHERID on queryLog (launcherId);

ALTER TABLE HARREQUESTRESPONSE ADD IF NOT EXISTS SCRIPTREPORTID VARCHAR(512);
ALTER TABLE HARREQUESTRESPONSE ADD IF NOT EXISTS SUITEREPORTID VARCHAR(512);
ALTER TABLE HARREQUESTRESPONSE ADD IF NOT EXISTS URL VARCHAR(4092);
ALTER TABLE HARREQUESTRESPONSE ADD IF NOT EXISTS STEPID VARCHAR(255);
ALTER TABLE HARREQUESTRESPONSE ADD IF NOT EXISTS LOADCOUNT VARCHAR(255);
ALTER TABLE stepReports ALTER COLUMN `screenShot` VARCHAR(4000) ;
