CREATE TABLE SUITEREPORTS (ID BIGINT NOT NULL IDENTITY(1,1)PRIMARY KEY CLUSTERED, SUITEREPORTID VARCHAR(255), SUITENAME VARCHAR(2000), SUITEPATH VARCHAR(2000), STARTTIME DATETIME, ENDTIME DATETIME, STATUS VARCHAR(255), TOTALCOUNT INT, PASSEDCOUNT INT, FAILEDCOUNT INT, TIMETAKEN INT, BROWSERTYPE VARCHAR(255));


CREATE TABLE NODEREPORTS(ID BIGINT NOT NULL IDENTITY(1,1)PRIMARY KEY CLUSTERED, SUITEREPORTID VARCHAR(255), HOST VARCHAR(255), PORT VARCHAR(255), SCRIPTCOUNT INT);
CREATE TABLE SCRIPTREPORTS(ID BIGINT NOT NULL IDENTITY(1,1)PRIMARY KEY CLUSTERED, SCRIPTREPORTID VARCHAR(255), SCRIPTNAME VARCHAR(2000), SUITENAME VARCHAR(2000), SUITEREPORTID VARCHAR(255), TOTALSTEPS INT, FAILURES INT, ERRORS INT, TIMETAKEN INT, NODEHOST VARCHAR(255), NODEPORT VARCHAR(255), STATUS VARCHAR(255), [LOAD] INT);
CREATE TABLE STEPREPORTS(ID BIGINT NOT NULL IDENTITY(1,1)PRIMARY KEY CLUSTERED, [MESSAGE] VARCHAR(2000), [DEBUGINFO] VARCHAR(2000), MESSAGETYPE VARCHAR(255), SCRIPTREPORTID VARCHAR(255), FAILUREMESSAGE VARCHAR(4000), MESSAGETIMESTAMP DATETIME);
CREATE TABLE TESTCASEREPORTS(ID BIGINT NOT NULL IDENTITY(1,1)PRIMARY KEY CLUSTERED, TESTCASEREPORTID VARCHAR(255), SCRIPTREPORTID VARCHAR(255), SUITEREPORTID VARCHAR(255), DESCRIPTION VARCHAR(4000), STATUS VARCHAR(255), TIMETAKEN INT, SCRIPTNAME VARCHAR(2000));
CREATE TABLE CSVREPORTS(ID BIGINT NOT NULL IDENTITY(1,1)PRIMARY KEY CLUSTERED, SUITEREPORTID VARCHAR(255), CSV VARCHAR(8000));
CREATE TABLE SAHIINFO([KEY] VARCHAR(255), VALUE VARCHAR(255));


CREATE INDEX SUITEREPORTS_SUITE_REPORT_ID ON SUITEREPORTS (SUITEREPORTID);
CREATE INDEX NODEPORTS_SUITE_REPORT_ID ON NODEREPORTS (SUITEREPORTID);
CREATE INDEX SCRIPTREPORTS_SUITE_REPORT_ID ON SCRIPTREPORTS (SUITEREPORTID);
CREATE INDEX SCRIPTREPORTS_SCRIPT_REPORT_ID ON SCRIPTREPORTS (SCRIPTREPORTID);
CREATE INDEX STEPREPORTS_SCRIPT_REPORT_ID ON STEPREPORTS (SCRIPTREPORTID);
CREATE INDEX TESTCASEREPORTS_SUITE_REPORT_ID ON TESTCASEREPORTS (SUITEREPORTID);
CREATE INDEX TESTCASEREPORTS_SCRIPT_REPORT_ID ON TESTCASEREPORTS (SCRIPTREPORTID);
CREATE INDEX TESTCASEREPORTS_TESTCASE_REPORT_ID ON TESTCASEREPORTS (TESTCASEREPORTID);
CREATE INDEX CSVREPORTS_SUITE_REPORT_ID ON CSVREPORTS (SUITEREPORTID);



ALTER TABLE STEPREPORTS ADD SCREENSHOT VARCHAR(255);
ALTER TABLE SUITEREPORTS ADD SUITEINFO VARCHAR(4000);
ALTER TABLE SUITEREPORTS ADD USERDEFINEDID VARCHAR(255);
ALTER TABLE STEPREPORTS ALTER COLUMN [DEBUGINFO] VARCHAR(4000);
ALTER TABLE STEPREPORTS ALTER COLUMN [MESSAGE] VARCHAR(4000); 

ALTER TABLE CSVREPORTS ALTER COLUMN CSV TEXT;
ALTER TABLE SCRIPTREPORTS ADD TCCOUNT INT;  
ALTER TABLE SCRIPTREPORTS ADD TCPASSED INT;
ALTER TABLE SCRIPTREPORTS ADD TCFAILED INT;
ALTER TABLE SUITEREPORTS ADD TCCOUNT INT;
ALTER TABLE SUITEREPORTS ADD TCPASSED INT;
ALTER TABLE SUITEREPORTS ADD TCFAILED INT;


ALTER TABLE STEPREPORTS ADD STEPID INT;


CREATE TABLE HARPAGES(id VARCHAR(767) PRIMARY KEY, PAGEDATA TEXT, REQUESTSTARTTIME VARCHAR(100));
CREATE TABLE HARREQUESTRESPONSE(id VARCHAR(767), REQUESTRESPONSEDATA TEXT, SENDTIME BIGINT, WAITTIME BIGINT, RECEIVETIME BIGINT, PRIMARY KEY(id));
CREATE TABLE QUERYLOG (ID BIGINT NOT NULL IDENTITY(1,1)PRIMARY KEY CLUSTERED, launcherId VARCHAR(255), query TEXT);
CREATE INDEX QUERYLOG_ID on QUERYLOG (id);   
CREATE INDEX HARPAGES_ID on harPages (id);
CREATE INDEX HAR_REQUEST_RESPONSE_ID on harPages (id);
ALTER TABLE SCRIPTREPORTS ADD scriptRelPath VARCHAR(1000);
ALTER TABLE SCRIPTREPORTS ADD startUrl VARCHAR(4000);
ALTER TABLE SCRIPTREPORTS ADD launcherId VARCHAR(255);
ALTER TABLE SCRIPTREPORTS ADD scriptArgs VARCHAR(5000);

CREATE INDEX QUERYLOG_LAUNCHERID on QUERYLOG (launcherId);

ALTER TABLE HARREQUESTRESPONSE ADD SCRIPTREPORTID VARCHAR(512);
ALTER TABLE HARREQUESTRESPONSE ADD SUITEREPORTID VARCHAR(512);
ALTER TABLE HARREQUESTRESPONSE ADD URL VARCHAR(4092);
ALTER TABLE HARREQUESTRESPONSE ADD STEPID VARCHAR(255);
ALTER TABLE HARREQUESTRESPONSE ADD LOADCOUNT VARCHAR(255);

ALTER TABLE STEPREPORTS ALTER COLUMN [SCREENSHOT] VARCHAR(4000); 
